# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Excel Fencing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Excel Fencing App

    # Add the pod for the Dialogflow Chatbot Agent
    pod 'ApiAI'


    # Add the pod for Firebase for Google Analytics
    pod 'Firebase/Analytics'

    # Add the pod for Password Login Identification
    pod 'Firebase/Auth'

    # Add the pod for Firebase Core
    pod 'Firebase/Core'

    # Add the pod for Firebase Database
    pod 'Firebase/Database'

    # Add the pod for Firestore
    pod 'Firebase/Firestore'

    # add pods for any other desired Firebase products
    # https://firebase.google.com/docs/ios/setup#available-pods

    # Add the pod for charts
    pod 'Charts'

end
